1. Create a 1D array of numbers from 0 to 9.

In [1]:
import numpy as np
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3×3 numpy array of all True’s

In [2]:
xd = np.ones((3, 3), dtype=bool)
xd

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Given an array as input, print only odd numbers as output

In [3]:
ao = np.arange(0,21)
ao
for i in range(len(ao)):
    if i%2 != 0:
        print(i)

1
3
5
7
9
11
13
15
17
19


4. Replace all odd numbers in arr with -2

In [4]:
ao[ao%2 != 0] = -2
ao

array([ 0, -2,  2, -2,  4, -2,  6, -2,  8, -2, 10, -2, 12, -2, 14, -2, 16,
       -2, 18, -2, 20])

5. How to reshape an array?

In [5]:
ao = ao.reshape((7,3))
print(ao,ao.shape)

[[ 0 -2  2]
 [-2  4 -2]
 [ 6 -2  8]
 [-2 10 -2]
 [12 -2 14]
 [-2 16 -2]
 [18 -2 20]] (7, 3)


6. Convert a 1D array to a 2D array with 2 rows

In [6]:
ar = np.arange(0,6)
ar 

array([0, 1, 2, 3, 4, 5])

In [7]:
ax = np.reshape(ar,(2,3))
ax

array([[0, 1, 2],
       [3, 4, 5]])

7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [8]:
a = np.arange(1,10)
print ('Original Array is:')
print (a)
print ('Modified array is:')
for i in np.nditer(a):
        if i%2 != 0 or i%4 == 0:
            print(i)


Original Array is:
[1 2 3 4 5 6 7 8 9]
Modified array is:
1
3
4
5
7
8
9


8. Given array, check if there are any null values and print them out. 


In [9]:
an = np.array([1, 0, np.nan, np.nan])
print("Original array")
print(an)
print("Test element-wise for NaN:")
print(np.isnan(an))


Original array
[ 1.  0. nan nan]
Test element-wise for NaN:
[False False  True  True]


9. How to replace all missing values with 0 in a numpy array?

In [10]:
ar = np.array([1, 1, 2,np.nan, 5, 8, np.nan])
ar



array([ 1.,  1.,  2., nan,  5.,  8., nan])

In [11]:
out_ar = np.nan_to_num(ar)  
out_ar

array([1., 1., 2., 0., 5., 8., 0.])

10. How to find the count of each unique number in a NumPy array?

In [12]:
au = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(au)
unique_elements, counts_elements = np.unique(au, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))


Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


11. How to convert a numeric to a categorical (text) array?

In [13]:
au

array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

In [14]:
new = au.astype(str)
new

array(['10', '10', '20', '10', '20', '20', '20', '30', '30', '50', '40',
       '40'], dtype='<U11')

12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.

In [15]:
ay = np.arange(99,300)

In [16]:
for i in np.nditer(ay):
        if i%5 == 0 or i%7 == 0:
            for i in np.nditer(ay):
                if i%5 == 0 and i%7 == 0:
                    ay.remove(i)
                    print(ay)

                
                    


AttributeError: 'numpy.ndarray' object has no attribute 'remove'

13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [18]:
ini_array = np.array([1, 2, 3, 6, 4, 5]) 

In [20]:
res = ini_array[::-1] 
print("final array", str(res)) 

final array [5 4 6 3 2 1]
